<?php
__( 'Grid View', 'radio-station' );
__( 'Calendar View', 'radio-station' );
__( 'Red', 'radio-station' );
__( 'Orange', 'radio-station' );
__( 'Yellow', 'radio-station' );
__( 'Light Green', 'radio-station' );
__( 'Green', 'radio-station' );
__( 'Cyan', 'radio-station' );
__( 'Light Blue', 'radio-station' );
__( 'Blue', 'radio-station' );
__( 'Purple', 'radio-station' );
__( 'Magenta', 'radio-station' );
__( 'GeoIP Stream Blocking', 'radio-station' );
__( 'No GeoIP Blocking', 'radio-station' );
__( 'Live365 (only US, UK, Canada, Mexico', 'radio-station' );
__( 'Custom Country Blacklist', 'radio-station' );
__( 'Custom Country Whitelist', 'radio-station' );
__( 'Block streaming according to country, detected by user IP address.', 'radio-station' );
__( 'SG Rewind', 'radio-station' );
__( 'Enable stream support for StreamGuys Rewind service.', 'radio-station' );
__( 'Rewind Endpoint', 'radio-station' );
__( 'Endpoint URL for StreamGuys Rewind service.', 'radio-station' );
__( 'Station Tagline', 'radio-station' );
__( '', 'radio-station' );
__( 'Station Callsign', 'radio-station' );
__( 'Broadcast Frequency', 'radio-station' );
__( 'Text display to inform users of your main station frequency.', 'radio-station' );
__( 'Frequency Band', 'radio-station' );
__( 'n/a', 'radio-station' );
__( 'FM', 'radio-station' );
__( 'AM', 'radio-station' );
__( 'DAB', 'radio-station' );
__( 'Your station frequency band identifier.', 'radio-station' );
__( 'Station Text', 'radio-station' );
__( 'Text line phone number for the Station (for requests etc.', 'radio-station' );
__( 'Display Station Meta', 'radio-station' );
__( 'Tagline', 'radio-station' );
__( 'Frequency', 'radio-station' );
__( 'Location', 'radio-station' );
__( 'Timezone', 'radio-station' );
__( 'Display your Radio Station Meta in Player by default.', 'radio-station' );
__( 'Display Start Hour', 'radio-station' );
__( 'Midnight', 'radio-station' );
__( 'Noon', 'radio-station' );
__( 'Schedule displays will start from this hour instead of midnight.', 'radio-station' );
__( 'Episodes Archive Page', 'radio-station' );
__( 'Select the Page for displaying the Episode archive list.', 'radio-station' );
__( 'Automatic Display', 'radio-station' );
__( 'Replaces selected page content with default Episode Archive. Alternatively customize display using the shortcode:', 'radio-station' );
__( 'Team Archive Page', 'radio-station' );
__( 'Select the Page for displaying the Team archive list.', 'radio-station' );
__( 'Replaces selected page content with default Team Archive. Alternatively customize display using the shortcode:', 'radio-station' );
__( 'Team Tab Display', 'radio-station' );
__( 'No Team Display', 'radio-station' );
__( 'Separate Role Tabs', 'radio-station' );
__( 'Combined Team List', 'radio-station' );
__( 'Combined Team Grid', 'radio-station' );
__( 'How to display Show team members (eg. hosts, producers on a Show page.', 'radio-station' );
__( 'Time Spaced Grid', 'radio-station' );
__( 'Enable Grid View option for equalized time spacing and background imsges.', 'radio-station' );
__( 'Episode Player', 'radio-station' );
__( 'Radio Station Stream Player', 'radio-station' );
__( 'MediaElements (WordPress', 'radio-station' );
__( 'Which player to use on Episode pages for the latest show recording.', 'radio-station' );
__( 'Player Default', 'radio-station' );
__( 'Light', 'radio-station' );
__( 'Dark', 'radio-station' );
__( 'Episode Player Theme', 'radio-station' );
__( 'Episode Player Controls theme style (Radio Station Stream Player only,', 'radio-station' );
__( 'Use Latest Episode', 'radio-station' );
__( 'Automatically use the latest Episode URL for the player embed on the Show page.', 'radio-station' );
__( 'Responsive Mode', 'radio-station' );
__( 'Horizontal Arrows', 'radio-station' );
__( 'Vertical Expander', 'radio-station' );
__( 'Player bar responsive mode for mobile overflow sections.', 'radio-station' );
__( 'Popup Player Button', 'radio-station' );
__( 'Add button to open Popup Player in separate window.', 'radio-station' );
__( 'Player Bar Height', 'radio-station' );
__( 'Set the height of the Sitewide Player Bar in pixels.', 'radio-station' );
__( 'Display Current Show', 'radio-station' );
__( 'Display the Current Show in the Player Bar.', 'radio-station' );
__( 'Show Meta Display', 'radio-station' );
__( 'Hosts', 'radio-station' );
__( 'Producers', 'radio-station' );
__( 'Shift Time', 'radio-station' );
__( 'Remaining Time', 'radio-station' );
__( 'Description', 'radio-station' );
__( 'Show meta to display in the Player Bar.', 'radio-station' );
__( 'Page Load Timeout', 'radio-station' );
__( 'Number of milliseconds to wait for new Page to load before prompting or fading in anyway. Use 0 for instant display (if continuous playback is enabled.', 'radio-station' );
__( 'Load Fail Prompt', 'radio-station' );
__( 'Off', 'radio-station' );
__( 'Prompt on Timeout only', 'radio-station' );
__( 'Prompt on 404 Not Found only', 'radio-station' );
__( 'Prompt on 404 or Timeout', 'radio-station' );
__( 'Prompt on Timeout or any Error', 'radio-station' );
__( 'Whether to show a user prompt on page timeout and/or when there is an error (if continuous playback is enabled.', 'radio-station' );
__( 'Display Playing Track', 'radio-station' );
__( 'Display the currently playing song in the Player Bar, if a supported metadata format is available. (Icy Meta, Icecast, Shoutcast 1/2, Current Playlist', 'radio-station' );
__( 'Track Animation', 'radio-station' );
__( 'No Animation', 'radio-station' );
__( 'Left to Right Ticker', 'radio-station' );
__( 'Right to Left Ticker', 'radio-station' );
__( 'Back and Forth', 'radio-station' );
__( 'How to animate the currently playing track display.', 'radio-station' );
__( 'Metadata URL', 'radio-station' );
__( 'Now playing metadata is normally retrieved via the Stream URL. Use this setting if you need to provide an alternative metadata location.', 'radio-station' );
__( 'Store Track Metadata?', 'radio-station' );
__( 'Save now playing track metadata in a separate database table for later use.', 'radio-station' );
__( 'Radio Station needs to be installed and activated to use %s.', 'radio-station' );
__( 'Activate Radio Station', 'radio-station' );
__( 'Install Radio Station', 'radio-station' );
__( 'Your Radio Station plugin needs to be updated to work with %s.', 'radio-station' );
__( 'The required minimum version of the Radio Station plugin is:', 'radio-station' );
__( 'Update to Radio Station', 'radio-station' );
__( 'Development Version', 'radio-station' );
__( 'Sorry, you are not allowed to update plugins for this site.', 'radio-station' );
__( 'Update Plugin via Github', 'radio-station' );
__( 'Error. Could not connect to filesystem. Please install plugin update manually.', 'radio-station' );
__( 'Error. Downloading the plugin package failed. Please try again.', 'radio-station' );
__( 'Downloaded plugin package from:', 'radio-station' );
__( 'Package unzipped successfully.', 'radio-station' );
__( 'Package contents moved to plugin directory.', 'radio-station' );
__( 'The plugin has been updated, but could not be reactivated. Please reactivate it manually.', 'radio-station' );
__( 'The previous version of the plugin has been backed up if you need to restore it.', 'radio-station' );
__( 'Plugin reactivated successfully.', 'radio-station' );
__( 'Radio Station Settings', 'radio-station' );
__( 'Back to Plugins page.', 'radio-station' );
__( 'Settings', 'radio-station' );
__( 'Radio Station', 'radio-station' );
__( 'Export Playlists', 'radio-station' );
__( 'Account', 'radio-station' );
__( 'Extending', 'radio-station' );
__( 'You have multiple conflicting versions of Radio Station Pro activated.', 'radio-station' );
__( 'Please visit your Plugins page to deactivate the incorrect one.', 'radio-station' );
__( 'Radio Station Pro', 'radio-station' );
__( 'Thumbnail' );
__( 'Medium' );
__( 'Large' );
__( 'Full Size' );
__( 'Important: %s continuous player bar is active.', 'radio-station' );
__( 'This overrides the page fade in, load timeout and loader bar settings here.' );
__( 'Adjust those settings via your Radio Station settings page instead.', 'radio-station' );
__( '"%1$s" require "%2$s" to be installed and activated.', 'radio-station' );
__( 'Radio Station Elementor Widgets', 'radio-station' );
__( 'Elementor', 'radio-station' );
__( '"%1$s" require "%2$s" version %3$s or greater.', 'radio-station' );
__( 'PHP', 'radio-station' );
__( 'Guests', 'radio-station' );
__( 'Topics', 'radio-station' );
__( 'Episodes', 'radio-station' );
__( 'You can add past Show Episodes for automatic display on Show pages.', 'radio-station' );
__( 'Click here to add or edit Show Episodes.', 'radio-station' );
__( 'Episode Information', 'radio-station' );
__( 'Episode Image', 'radio-station' );
__( 'Set %s Avatar Image', 'radio-station' );
__( 'Remove %s Avatar Image', 'radio-station' );
__( 'Are you sure you want to remove this image?', 'radio-station' );
__( 'Select or Upload Image', 'radio-station' );
__( 'Use this Image', 'radio-station' );
__( 'Show', 'radio-station' );
__( 'Select Show', 'radio-station' );
__( 'Draft', 'radio-station' );
__( 'No Shows to Select.', 'radio-station' );
__( 'The Show this is an Episode for.', 'radio-station' );
__( 'Media Type', 'radio-station' );
__( 'File URL', 'radio-station' );
__( 'Media Library', 'radio-station' );
__( 'Use an existing URL or add to Media Library.', 'radio-station' );
__( 'Enter the absolute URL to the media source.', 'radio-station' );
__( 'Opens the Media Library for uploading.', 'radio-station' );
__( 'Disable Download', 'radio-station' );
__( 'Enable this to hide the Download icon next to the embedded player.', 'radio-station' );
__( 'Episode Number', 'radio-station' );
__( 'This Episode number is unique.', 'radio-station' );
__( 'This Episode number is in use!', 'radio-station' );
__( 'Highest', 'radio-station' );
__( 'Click to auto-number to highest episode plus one.', 'radio-station' );
__( 'Auto', 'radio-station' );
__( 'The Episode number in the Show series.', 'radio-station' );
__( 'Broadcast Date', 'radio-station' );
__( 'Date that the Episode aired.', 'radio-station' );
__( 'Broadcast Time', 'radio-station' );
__( 'The time that the Episode aired', 'radio-station' );
__( 'Episode Length', 'radio-station' );
__( 'minutes', 'radio-station' );
__( 'Linked Playlist', 'radio-station' );
__( 'Select Playlist', 'radio-station' );
__( 'No Playlists to Select.', 'radio-station' );
__( 'The Playlist data for this Episode.', 'radio-station' );
__( 'Set Episode Number to one above current highest?', 'radio-station' );
__( 'Select Audio File', 'radio-station' );
__( 'Remove Selected Audio', 'radio-station' );
__( 'Are you sure you want to remove this audio?', 'radio-station' );
__( 'Assign to Show Episode', 'radio-station' );
__( 'No Episode', 'radio-station' );
__( 'No Show Episodes found.', 'radio-station' );
__( 'No Show selected.', 'radio-station' );
__( 'Warning! This playlist is assigned to more than one episode.', 'radio-station' );
__( 'Number', 'radio-station' );
__( 'of', 'radio-station' );
__( 'Edit Show', 'radio-station' );
__( 'Episode Show', 'radio-station' );
__( 'All Shows', 'radio-station' );
__( 'Episode for Show', 'radio-station' );
__( 'Not Assigned', 'radio-station' );
__( 'No Shows available to Select.', 'radio-station' );
__( 'Episode', 'radio-station' );
__( 'Add Episode', 'radio-station' );
__( 'Edit Episode', 'radio-station' );
__( 'New Episode', 'radio-station' );
__( 'View Episode', 'radio-station' );
__( 'Search Episodes', 'radio-station' );
__( 'No Episodes found', 'radio-station' );
__( 'No Episodes found in Trash', 'radio-station' );
__( 'All Episodes', 'radio-station' );
__( 'Post Type for Show Episodes', 'radio-station' );
__( 'Search Topics', 'radio-station' );
__( 'All Topics', 'radio-station' );
__( 'Parent Topic', 'radio-station' );
__( 'Parent Topic:', 'radio-station' );
__( 'Edit Topic', 'radio-station' );
__( 'Update Topic', 'radio-station' );
__( 'Add New Topic', 'radio-station' );
__( 'New Topic Name', 'radio-station' );
__( 'Topic', 'radio-station' );
__( 'Search Guests', 'radio-station' );
__( 'All Guests', 'radio-station' );
__( 'Parent Guest', 'radio-station' );
__( 'Parent Guest:', 'radio-station' );
__( 'Edit Guest', 'radio-station' );
__( 'Update Guest', 'radio-station' );
__( 'Add New Guest', 'radio-station' );
__( 'New Guest Name', 'radio-station' );
__( 'Guest', 'radio-station' );
__( 'Show %s', 'radio-station' );
__( 'and', 'radio-station' );
__( 'Aired on', 'radio-station' );
__( 'at', 'radio-station' );
__( 'Image', 'radio-station' );
__( 'Add Genre Image', 'radio-station' );
__( 'Remove Genre Image', 'radio-station' );
__( 'Background Color', 'radio-station' );
__( 'Border Color', 'radio-station' );
__( 'Text Color', 'radio-station' );
__( 'Insert', 'radio-station' );
__( 'this is a success message', 'radio-station' );
__( 'this is a failure message', 'radio-station' );
__( 'Please upload a valid YAML file.', 'radio-station' );
__( 'Please upload a valid YAML file' );
__( 'Please upload a file to import.', 'radio-station' );
__( 'Please upload a file to import' );
__( 'Successfully parsed and imported YAML file, deleting pre-existing show data.', 'radio-station' );
__( 'Successfully parsed and imported YAML file. Pre-existing show data remains unchanged.', 'radio-station' );
__( 'Export successful. Use the following link(s to download your data.', 'radio-station' );
__( 'Data file', 'radio-station' );
__( 'Image zip file', 'radio-statoin' );
__( 'Image tgz file', 'radio-station' );
__( 'Download one of the image files and the data file. See help for details on how to stage an import including images.', 'radio-station' );
__( 'Show data file (YAML', 'radio-station' );
__( 'Images not exported. See help for details on how to include images.', 'radio-station' );
__( 'YAML import error. See below for details.', 'radio-station' );
__( 'Failed to create export folder', 'radio-station' );
__( 'No image exported for', 'radio-station' );
__( 'Failed to copy file. See below for details', 'radio-station' );
__( 'Failed to create show_images.zip', 'radio-station' );
__( 'Each show in the YAML file must define at minimum the following keys: ', 'radio-station' );
__( 'show-title: may not be null.', 'radio-station' );
__( 'show-description: may not be null.', 'radio-station' );
__( 'show-image: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-avatar: must be a URL reference to an existing image.', 'radio-station' );
__( 'show-header: must be a URL reference to an existing image.', 'radio-station' );
__( 'upload-images: may not be null.', 'radio-station' );
__( 'show-url: must be a valid web address.', 'radio-station' );
__( 'show-podcast: must be a valid web address.', 'radio-station' );
__( 'show-user-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-producer-list: must be a simple array of valid email addresses.', 'radio-station' );
__( 'show-email: must be a valid email address.', 'radio-station' );
__( 'show-active: may not be null.', 'radio-station' );
__( 'YAML data parsed successfully, but contains formatting errors. See below for details.', 'radio-station' );
__( 'Data file errors noted as follows:', 'radio-station' );
__( 'show-schedule[<weekday>] time blocks must be in 24h format and have the form "04:55" (note 0 padding.', 'radio-station' );
__( 'Error, for show-schedule[<weekday>], only "disabled" and "encore" flags are allowed', 'radio-station' );
__( 'show-schedule[<weekday>] must reference an array of time blocks containing at least one element.', 'radio-station' );
__( 'Invalid weekday. show-schedule[<weekday>] must be one of "sun".."sat", or "sunday".."saturday" (case insensitive.', 'radio-station' );
__( ' show-schedule: must define at least one weekday.', 'radio-station' );
__( 'Import/Export Show Data', 'radio-station' );
__( 'Import/Export', 'radio-station' );
__( 'Import', 'radio-station' );
__( 'Import show data from a YAML file.', 'radio-station' );
__( 'Delete existing show data', 'radio-station' );
__( 'WARNING', 'radio-station' );
__( 'Export', 'radio-station' );
__( 'Export show data to a downloadable file. Does not include images by default. Check Advanced for additional options.', 'radio-station' );
__( 'Advanced', 'radio-station' );
__( 'YAML file name', 'radio-station' );
__( 'Default similar to', 'radio-station' );
__( 'URL where show images will be staged for import (see help', 'radio-station' );
__( 'Metadata Source', 'radio-station' );
__( 'Default Plugin Setting', 'radio-station' );
__( 'Override: Metadata On', 'radio-station' );
__( 'Override: Metadata Off', 'radio-station' );
__( 'Override: Metadata URL', 'radio-station' );
__( 'Override: Current Playlist', 'radio-station' );
__( 'Metadata Override URL', 'radio-station' );
__( 'Sorry, this stream is unavailable in your country.', 'radio-station' );
__( 'Station', 'radio-station' );
__( 'Player', 'radio-station' );
__( 'Color Options', 'radio-station' );
__( 'Player Text Color', 'radio-station' );
__( 'Player Background Color', 'radio-station' );
__( 'Playing Color', 'radio-station' );
__( 'Buttons Color', 'radio-station' );
__( 'Track Color', 'radio-station' );
__( 'Track Thumb Color', 'radio-station' );
__( 'Advanced Options', 'radio-station' );
__( 'Plugin Setting', 'radio-station' );
__( 'On', 'radio-station' );
__( 'Current Show Display', 'radio-station' );
__( 'Now Playing Track Display', 'radio-station' );
__( 'Leave blank to use stream URL.', 'radio-station' );
__( 'Custom Theme', 'radio-station' );
__( 'Close', 'radio-station' );
__( 'Expand', 'radio-station' );
__( 'Collapse', 'radio-station' );
__( 'Popup Player to separate window.', 'radio-station' );
__( 'Popup Player', 'radio-station' );
__( 'Popup', 'radio-station' );
__( 'Start Audio Playback?', 'radio-station' );
__( 'Yes', 'radio-station' );
__( 'No', 'radio-station' );
__( 'Resume Audio Playback?', 'radio-station' );
__( 'Edit Your Host Profile', 'radio-station' );
__( 'Host Profile', 'radio-station' );
__( 'Edit Your Producer Profile', 'radio-station' );
__( 'Producer Profile', 'radio-station' );
__( 'You do not have permission to do that.', 'radio-station' );
__( 'Profile Information', 'radio-station' );
__( 'Website Link', 'radio-station' );
__( '%s Email', 'radio-station' );
__( '%s Phone', 'radio-station' );
__( 'Patreon Page ID', 'radio-station' );
__( 'Host Image', 'radio-station' );
__( 'Producer Image', 'radio-station' );
__( 'User Save Error! The selected User is already assigned to a %s Profile.', 'radio-station' );
__( 'Host User', 'radio-station' );
__( 'Producer User', 'radio-station' );
__( 'Team', 'radio-station' );
__( 'View', 'radio-station' );
__( 'All', 'radio-station' );
__( 'Editors', 'radio-station' );
__( 'Shows', 'radio-station' );
__( 'Recurring Overrides', 'radio-station' );
__( 'Clear Recurrences', 'radio-station' );
__( 'Save Recurrences', 'radio-station' );
__( 'Add Recurrence', 'radio-station' );
__( 'Saving Recurrences...', 'radio-station' );
__( 'Recurrences Saved.', 'radio-station' );
__( 'Single Overrides', 'radio-station' );
__( 'Channel', 'radio-station' );
__( 'Start Date', 'radio-station' );
__( 'Start Time', 'radio-station' );
__( 'End Time', 'radio-station' );
__( 'Disabled', 'radio-station' );
__( 'Multiday', 'radio-station' );
__( 'Repeats', 'radio-station' );
__( 'Once Every Month', 'radio-station' );
__( 'By Week Intervals', 'radio-station' );
__( 'Every', 'radio-station' );
__( 'Weeks', 'radio-station' );
__( 'On the', 'radio-station' );
__( 'First', 'radio-station' );
__( 'Second', 'radio-station' );
__( 'Third', 'radio-station' );
__( 'Fourth', 'radio-station' );
__( 'Fifth', 'radio-station' );
__( 'Last', 'radio-station' );
__( 'Cutoff Date', 'radio-station' );
__( 'List Recurrence Dates', 'radio-station' );
__( 'Preview Recurrence Dates', 'radio-station' );
__( 'Duplicate Recurrence', 'radio-station' );
__( 'Remove Recurrence', 'radio-station' );
__( 'Are you sure you want to remove this Recurrence?', 'radio-station' );
__( 'Are you sure you want to clear all Recurrences?', 'radio-station' );
__( 'Extra Days', 'radio-station' );
__( 'Number of Weeks', 'radio-station' );
__( 'Preview Recurrences', 'radio-station' );
__( 'Expired. Publish or Update instead.', 'radio-station' );
__( 'Failed. Invalid Override.', 'radio-station' );
__( 'Failed. Publish or Update instead.', 'radio-station' );
__( 'Warning! Recurring conflicts detected.', 'radio-station' );
__( 'Error! Override not found.', 'radio-station' );
__( 'Error! No matching recurrence found.', 'radio-station' );
__( 'Error! No saved recurrences were found.', 'radio-station' );
__( 'Cannot list recurring times without a valid start time.', 'radio-station' );
__( 'Cannot list recurring times without a valid end time.', 'radio-station' );
__( 'Cannot list recurring times when end date is before start date.', 'radio-station' );
__( 'Override Date', 'radio-station' );
__( 'Shows Affected', 'radio-station' );
__( 'Error. Could not generate shift preview list for times specified. Check your entries and try again.', 'radio-station' );
__( 'DJs / Hosts', 'radio-station' );
__( 'Show Editors', 'radio-station' );
__( 'Role Assignment Interface', 'radio-station' );
__( 'You can assign Radio Station roles to users directly here.', 'radio-station' );
__( 'They can also be assigned via the WordPress user editor.', 'radio-station' );
__( 'Grant Role to User(s', 'radio-station' );
__( 'Remove Role from User(s', 'radio-station' );
__( 'Update User Roles', 'radio-station' );
__( 'You have unsaved role changes.', 'radio-station' );
__( 'role added to user', 'radio-station' );
__( 'role removed from user', 'radio-station' );
__( 'Schedule', 'radio-station' );
__( 'Schedule Editor', 'radio-station' );
__( 'Visual Schedule Editor', 'radio-station' );
__( 'Table', 'radio-station' );
__( 'Tabs', 'radio-station' );
__( 'Grid', 'radio-station' );
__( 'Calendar', 'radio-station' );
__( 'Your session has expired. You can log in again from this page or go to the login page.' );
__( 'You have unsaved changes. Are you sure you want to close this window?', 'radio-station' );
__( 'Save Shift', 'radio-station' );
__( 'Save Shifts', 'radio-station' );
__( 'Save Override', 'radio-station' );
__( 'Save Overrides', 'radio-station' );
__( 'Save Recurrence', 'radio-station' );
__( 'Edit Show Shifts', 'radio-station' );
__( 'Edit Override Times', 'radio-station' );
__( 'Edit Show Shift', 'radio-station' );
__( 'Edit Override Time', 'radio-station' );
__( 'Add to Schedule', 'radio-station' );
__( 'Add Show or Override to Schedule', 'radio-station' );
__( 'Error. Provided Show ID does not exist.', 'radio-station' );
__( 'You do not have permission to do that.', 'radio_station' );
__( 'Warning. Provided Shift ID is not valid.', 'radio-station' );
__( 'Warning. Provided Shift ID no longer exists.', 'radio-station' );
__( 'Display Shifts', 'radio-station' );
__( 'Selected Shift', 'radio-station' );
__( 'All Show Shifts', 'radio-station' );
__( 'Warning. Provided Override Shift ID no longer exists.', 'radio-station' );
__( 'Override', 'radio-station' );
__( 'Display Override', 'radio-station' );
__( 'Selected Override Time', 'radio-station' );
__( 'All Override Times', 'radio-station' );
__( 'Error. Provided ID is not a Show or Override.', 'radio-station' );
__( 'Error! Invalid date value passed.', 'radio-station' );
__( 'Error! Invalid day value passed.', 'radio-station' );
__( 'Timeslot Type', 'radio-station' );
__( 'Show Shift', 'radio-station' );
__( 'Schedule Override', 'radio-station' );
__( 'Recurring Override', 'radio-station' );
__( 'Timeslot Date', 'radio-station' );
__( 'End Date', 'radio-station' );
__( 'Shift Day', 'radio-station' );
__( 'Encore', 'radio-station' );
__( 'Target Show', 'radio-station' );
__( 'Add to Existing Show', 'radio-station' );
__( 'Create New Show', 'radio-station' );
__( 'Target Special', 'radio-station' );
__( 'Add to Existing Special', 'radio-station' );
__( 'Create New Special', 'radio-station' );
__( 'Select Show...', 'radio-station' );
__( 'Add Shift to Show', 'radio-station' );
__( 'Select Special...', 'radio-station' );
__( 'Add to Special', 'radio-station' );
__( 'Open in a New Window', 'radio-station' );
__( 'Clear Shifts', 'radio-station' );
__( 'Add Shift', 'radio-station' );
__( 'Adding Show Shift...', 'radio-station' );
__( 'Show Shift Added.', 'radio-station' );
__( 'Adding Override Timeslot...', 'radio-station' );
__( 'Override Timeslot Saved.', 'radio-station' );
__( 'Clear Overrides', 'radio-station' );
__( 'Add Override', 'radio-station' );
__( 'Add Recurrences', 'radio-station' );
__( 'Adding Reccurence Timeslot...', 'radio-station' );
__( 'Recurrence Timeslot Saved.', 'radio-station' );
__( 'Load Schedule for Previous Week', 'radio-station' );
__( 'Load Schedule for Next Week', 'radio-station' );
__( 'List', 'radio-station' );
__( 'No Hosts were found to display.', 'radio-station' );
__( 'No Producers were found to display.', 'radio-station' );
__( 'No Episodes were found to display.', 'radio-station' );
__( 'Published on ', 'radio-station' );
__( 'No %s were found to display.', 'radio-station' );
__( 'Social Icons', 'radio-station' );
__( 'Soundcloud', 'radio-station' );
__( 'Mixcloud', 'radio-station' );
__( 'Spotify', 'radio-station' );
__( 'Twitch', 'radio-station' );
__( 'Discord', 'radio-station' );
__( 'Facebook', 'radio-station' );
__( 'Twitter', 'radio-station' );
__( 'YouTube', 'radio-station' );
__( 'LinkedIn', 'radio-station' );
__( 'Xing', 'radio-station' );
__( 'Instagram', 'radio-station' );
__( 'WhatsApp', 'radio-station' );
__( 'Pinterest', 'radio-station' );
__( 'Custom', 'radio-station' );
__( 'Add a Social Icon', 'radio-station' );
__( 'Move this Icon Up', 'radio-station' );
__( 'Move this Icon Down', 'radio-station' );
__( 'Remove this Social Icon', 'radio-station' );
__( 'URL', 'radio-station' );
__( 'Icon URL', 'radio-station' );
__( 'Unknown', 'radio-station' );
__( 'Social URL Page Link', 'radio-station' );
__( 'Social Icon Image URL', 'radio-station' );
__( 'Are you sure you want to remove this Social Icon?', 'radio-station' );
__( 'No Social Icon Services defined.', 'radio-station' );
__( 'You can reorder this icon after saving it.', 'radio-station' );
__( 'Change Timezone', 'radio-station' );
__( 'Select Region...', 'radio-station' );
__( 'Clear', 'radio-station' );
__( 'Cancel', 'radio-station' );
__( 'Select Timezone...', 'radio-station' );
__( 'Default', 'radio-station' );
__( 'Automatic Changeover Reloading', 'radio-station' );
__( 'to', 'radio-station' );
__( 'with', 'radio-station' );
__( 'encore airing', 'radio-station' );
__( 'Audio File', 'radio-station' );
__( 'Genres', 'radio-station' );
__( 'No Shows', 'radio-station' );
__( 'No scheduled Shows found for this date.', 'radio-station' );
__( 'Previous Day', 'radio-station' );
__( 'Next Day', 'radio-station' );
__( 'Viewing', 'radio-station' );
__( 'No Shows scheduled.', 'radio-station' );
__( 'Show RSS Feed', 'radio-station' );
__( 'Become a Supporter for', 'radio-station' );
__( 'Episode Info', 'radio-station' );
__( 'Broadcasted', 'radio-station' );
__( 'on', 'radio-station' );
__( 'Hosted by', 'radio-station' );
__( 'Produced by', 'radio-station' );
__( 'Show More', 'radio-station' );
__( 'Show Less', 'radio-station' );
__( 'Listen to this %s', 'radio-station' );
__( 'Download this Episode', 'radio-station' );
__( 'About this %s', 'radio-station' );
__( 'About', 'radio-station' );
__( '%s Show', 'radio-station' );
__( '%s Playlist', 'radio-station' );
__( 'Jump to', 'radio-station' );
__( 'Visit %s Website', 'radio-station' );
__( '%s Phone Number', 'radio-station' );
__( 'Email %s', 'radio-station' );
__( '%s RSS Feed', 'radio-station' );
__( 'Download Latest Broadcast', 'radio-station' );
__( 'Profile Info', 'radio-station' );
__( 'Website', 'radio-station' );
__( 'Email', 'radio-station' );
__( 'Phone', 'radio-station' );
__( 'Archive List', 'radio-station' );
__( 'Archive list for Radio Station record types.', 'radio-station' );
__( 'General', 'radio-station' );
__( 'Archive List Details', 'radio-station' );
__( 'Archive Type', 'radio-station' );
__( 'Overrides', 'radio-station' );
__( 'Playlists', 'radio-station' );
__( 'Shows by Genre', 'radio-station' );
__( 'Shows by Language', 'radio-station' );
__( 'Archive View', 'radio-station' );
__( 'List View', 'radio-station' );
__( 'Records Per Page', 'radio-station' );
__( 'Use 0 for all records.', 'radio-station' );
__( 'Display Pagination?', 'radio-station' );
__( 'Hide if Empty?', 'radio-station' );
__( 'Archive Query', 'radio-station' );
__( 'Order By', 'radio-station' );
__( 'Title', 'radio-station' );
__( 'Published Date', 'radio-station' );
__( 'Modified Date', 'radio-station' );
__( 'Order', 'radio-station' );
__( 'Ascending', 'radio-station' );
__( 'Descending', 'radio-station' );
__( 'Archive Record Display', 'radio-station' );
__( 'Time Display Format', 'radio-station' );
__( '12 Hour', 'radio-station' );
__( '24 Hour', 'radio-station' );
__( 'Description Display Format', 'radio-station' );
__( 'View Default', 'radio-station' );
__( 'None', 'radio-station' );
__( 'Excerpt', 'radio-station' );
__( 'Full', 'radio-station' );
__( 'Display Image?', 'radio-station' );
__( 'This setting is for Shows and Overrides.', 'radio-station' );
__( 'Only Shows with Shifts?', 'radio-station' );
__( 'This setting is for Shows only.', 'radio-station' );
__( 'Display Override Dates?', 'radio-station' );
__( 'This setting is for Overrides only.', 'radio-station' );
__( 'Style', 'radio-station' );
__( 'Container Styles', 'radio-station' );
__( 'Alignment', 'radio-station' );
__( 'Typography', 'radio-station' );
__( 'Title Text Color', 'radio-station' );
__( 'Title Typography', 'radio-station' );
__( 'Description Text Color', 'radio-station' );
__( 'Description Typography', 'radio-station' );
__( 'Meta Text Color', 'radio-station' );
__( 'Meta Typography', 'radio-station' );
__( 'Radio Clock', 'radio-station' );
__( 'Radio Station Clock time display.', 'radio-station' );
__( 'Radio Clock Display Options', 'radio-station' );
__( 'Day Display Format', 'radio-station' );
__( 'Short', 'radio-station' );
__( 'Display Date?', 'radio-station' );
__( 'Month Display Format', 'radio-station' );
__( 'Display Timezone?', 'radio-station' );
__( 'Display Seconds?', 'radio-station' );
__( 'Label Text Color', 'radio-station' );
__( 'Label Typography', 'radio-station' );
__( 'Times Text Color', 'radio-station' );
__( 'Times Typography', 'radio-station' );
__( 'Timezone Switcher Text Color', 'radio-station' );
__( 'Timezone Switcher Typography', 'radio-station' );
__( 'Current Playlist', 'radio-station' );
__( 'Current Playlist module for Radio Station.', 'radio-station' );
__( 'Loading Options', 'radio-station' );
__( 'AJAX Loading', 'radio-station' );
__( 'To bypass page caching.', 'radio-station' );
__( 'Dynamic Reloading', 'radio-station' );
__( 'Reload at Show changeovers.', 'radio-station' );
__( 'No Current Playlist Text', 'radio-station' );
__( 'Blank for default. 0 for none.', 'radio-station' );
__( 'Extra Display Options', 'radio-station' );
__( 'Display Playlist Title', 'radio-station' );
__( 'Link to Playlist Page', 'radio-station' );
__( 'Remaining Time Countdown', 'radio-station' );
__( 'Show Time Display Options', 'radio-station' );
__( 'Display Song Title', 'radio-station' );
__( 'Display Artist', 'radio-station' );
__( 'Display Album', 'radio-station' );
__( 'Display Record Label', 'radio-station' );
__( 'Display Track Comments', 'radio-station' );
__( 'Track Info Text Color', 'radio-station' );
__( 'Track Info Typography', 'radio-station' );
__( 'Playlist Title Text Color', 'radio-station' );
__( 'Playlist Title Typography', 'radio-station' );
__( 'Countdown Text Color', 'radio-station' );
__( 'Countdown Typography', 'radio-station' );
__( 'Current Show', 'radio-station' );
__( 'Current Show module for Radio Station.', 'radio-station' );
__( 'No Current Show Text', 'radio-station' );
__( 'Show Display Options', 'radio-station' );
__( 'Link to Show Page', 'radio-station' );
__( 'Title Position', 'radio-station' );
__( 'Above Image', 'radio-station' );
__( 'Left of Image', 'radio-station' );
__( 'Right of Image', 'radio-station' );
__( 'Below Image', 'radio-station' );
__( 'Display Show Image', 'radio-station' );
__( 'Image Size', 'radio-station' );
__( 'Image Width Override', 'radio-station' );
__( 'Display Show Time', 'radio-station' );
__( 'Display All Show Times', 'radio-station' );
__( 'Display Show Hosts', 'radio-station' );
__( 'Show Description Excerpt', 'radio-station' );
__( 'Display Show Playlist', 'radio-station' );
__( 'Display if Encore Airing', 'radio-station' );
__( 'Show Title Color', 'radio-station' );
__( 'Show Title Typography', 'radio-station' );
__( 'Show Description Text Color', 'radio-station' );
__( 'Show Description Typography', 'radio-station' );
__( 'Radio Player', 'radio-station' );
__( 'Radio Station Audio stream player module.', 'radio-station' );
__( 'Player Content', 'radio-station' );
__( 'Stream URL', 'radio-station' );
__( 'Leave blank to use default stream.', 'radio-station' );
__( 'Player Title Text', 'radio-station' );
__( 'Empty for default, 0 for none.', 'radio-station' );
__( 'Player Station Image', 'radio-station' );
__( 'Display Station Image', 'radio-station' );
__( 'Do Not Display Station Image', 'radio-station' );
__( 'Player Options', 'radio-station' );
__( 'Player Script', 'radio-station' );
__( 'Amplitude', 'radio-station' );
__( 'Howler', 'radio-station' );
__( 'jPlayer', 'radio-station' );
__( 'Initial Volume', 'radio-station' );
__( 'Volume Controls', 'radio-station' );
__( 'Volume Slider', 'radio-station' );
__( 'Up and Down Buttons', 'radio-station' );
__( 'Mute Button', 'radio-station' );
__( 'Maximize Button', 'radio-station' );
__( 'Use as Default Player', 'radio-station' );
__( 'Make this the default player on this page.', 'radio-station' );
__( 'Metadata Source URL', 'radio-station' );
__( 'Defaults to Stream URL.', 'radio-station' );
__( 'Player Design', 'radio-station' );
__( 'Player Layout', 'radio-station' );
__( 'Vertical (Stacked', 'radio-station' );
__( 'Horizontal (Inline', 'radio-station' );
__( 'Player Theme', 'radio-station' );
__( 'Player Buttons', 'radio-station' );
__( 'Circular', 'radio-station' );
__( 'Rounded', 'radio-station' );
__( 'Square', 'radio-station' );
__( 'Player Colors', 'radio-station' );
__( 'Playing Highlight Color', 'radio-station' );
__( 'Buttons Highlight Color', 'radio-station' );
__( 'Slider Track Color', 'radio-station' );
__( 'Slider Thumb Color', 'radio-station' );
__( 'Player Typography', 'radio-station' );
__( 'Station Text Color', 'radio-station' );
__( 'Station Typography', 'radio-station' );
__( 'Show Text Color', 'radio-station' );
__( 'Show Typography', 'radio-station' );
__( 'Song Track Text Color', 'radio-station' );
__( 'Song Track Typography', 'radio-station' );
__( 'Master Schedule', 'radio-station' );
__( 'Master Schedule module for Radio Station.', 'radio-station' );
__( 'Schedule Display Options', 'radio-station' );
__( 'Schedule View', 'radio-station' );
__( 'Ctrl-click to select multiple views.', 'radio-station' );
__( 'Table View', 'radio-station' );
__( 'Tabbed View', 'radio-station' );
__( 'Default View', 'radio-station' );
__( 'Image Position', 'radio-station' );
__( '[Tabbed View] Show avatar relative to Show text.', 'radio-station' );
__( 'left', 'radio-station' );
__( 'Right', 'radio-station' );
__( 'Hide Past Shows', 'radio-station' );
__( '[Tabbed View] Display only current and upcoming shows.', 'radio-station' );
__( 'Grid Width', 'radio-station' );
__( '[Grid View] Column width in pixels.', 'radio-station' );
__( '[Grid View] Line up Shows by times.', 'radio-station' );
__( 'Calendar Weeks', 'radio-station' );
__( '[Calendar View] Number of future weeks.', 'radio-station' );
__( 'Previous Weeks', 'radio-station' );
__( '[Calendar View] Number of past weeks.', 'radio-station' );
__( 'Header Display Options', 'radio-station' );
__( 'Radio Time Header', 'radio-station' );
__( 'Display Radio Clock', 'radio-station' );
__( 'Display Radio Timezone', 'radio-station' );
__( 'No Time Header', 'radio-station' );
__( 'Display Genre Highlighter', 'radio-station' );
__( 'Time Display Options', 'radio-station' );
__( 'Schedule Start Day', 'radio-station' );
__( 'WP Start of Week', 'radio-station' );
__( 'Today', 'radio-station' );
__( 'Monday', 'radio-station' );
__( 'Tuesday', 'radio-station' );
__( 'Wednesday', 'radio-station' );
__( 'Thursday', 'radio-station' );
__( 'Friday', 'radio-station' );
__( 'Saturday', 'radio-station' );
__( 'Sunday', 'radio-station' );
__( 'Link to Shows', 'radio-station' );
__( 'Display Show Description', 'radio-station' );
__( 'Link to Hosts', 'radio-station' );
__( 'Display Show Genres', 'radio-station' );
__( 'Display Encore', 'radio-station' );
__( 'Headers Text Color', 'radio-station' );
__( 'Headers Typography', 'radio-station' );
__( 'Subheaders Text Color', 'radio-station' );
__( 'Subheaders Typography', 'radio-station' );
__( 'Show Title Text Color', 'radio-station' );
__( 'Show Times Text Color', 'radio-station' );
__( 'Show Times Typography', 'radio-station' );
__( 'Schedule Colors', 'radio-station' );
__( 'Odd Headers Background Color', 'radio-station' );
__( 'Even Headers Background Color', 'radio-station' );
__( 'Active Header Background Color', 'radio-station' );
__( 'Current Show Border Color', 'radio-station' );
__( 'Upcoming Shows', 'radio-station' );
__( 'Upcoming Shows module for Radio Station.', 'radio-station' );
__( 'Upcoming Shows to Display', 'radio-station' );
__( 'No Upcoming Shows Text', 'radio-station' );
__( 'Radio Archive', 'radio-station' );
__( 'Archive Record Query', 'radio-station' );
__( 'Publish Date', 'radio-station' );
__( 'Clock Styling', 'radio-station' );
__( 'Archive Alignment', 'radio-station' );
__( 'Left', 'radio-station' );
__( 'Center', 'radio-station' );
__( 'Record Title Typography', 'radio-station' );
__( 'Record Description Typography', 'radio-station' );
__( 'Record Meta Typography', 'radio-station' );
__( 'Clock Alignment', 'radio-station' );
__( 'Radio Current Playlist', 'radio-station' );
__( 'Track Display Options', 'radio-station' );
__( 'Playlist Styling', 'radio-station' );
__( 'Text Alignment', 'radio-station' );
__( 'Playlist Label Typography', 'radio-station' );
__( 'Playlist Info Typography', 'radio-station' );
__( 'Radio Current Show', 'radio-station' );
__( 'Current Show Styling', 'radio-station' );
__( 'Player Alignment', 'radio-station' );
__( 'Station Text Typography', 'radio-station' );
__( 'Show Text Typography', 'radio-station' );
__( 'Radio Schedule', 'radio-station' );
__( 'Display Show Images', 'radio-station' );
__( 'Schedule Typography', 'radio-station' );
__( 'Radio Upcoming Shows', 'radio-station' );
__( 'Upcoming Shows Styling', 'radio-station' );
__( 'Broadcast Frequency', 'radio-station' );
__( 'Your station frequency as a number.', 'radio-station' );
__( 'Frequency Band', 'radio-station' );
__( 'n/a', 'radio-station' );
__( 'FM', 'radio-station' );
__( 'AM', 'radio-station' );
__( 'Your station frequency band identifier.', 'radio-station' );
__( 'Show Page Button', 'radio-station' );
__( 'Automatically add Subscibe button to Show pages.', 'radio-station' );
__( 'Show Archives Buttons', 'radio-station' );
__( 'Automatically add Subsscibe buttons to Show list archives.', 'radio-station' );
__( 'Table View', 'radio-station' );
__( 'Tabbed View', 'radio-station' );
__( 'List View', 'radio-station' );
__( 'Grid View', 'radio-station' );
__( 'Calendar View', 'radio-station' );
__( 'Schedule View Buttons', 'radio-station' );
__( 'Automatically add Subscribe buttons to selected Schedule views by default.', 'radio-station' );
__( 'Magic Login', 'radio-station' );
__( 'Enable passwordless magic Login email for users to manage their subscriptions.', 'radio-station' );
__( 'Magic Code', 'radio-station' );
__( 'Allow user to enter magic code from email rather than clicking magic link.', 'radio-station' );
__( 'Hide Subscriber Bar', 'radio-station' );
__( 'Do not display the WordPress Admin Bar for logged in Subscribers.', 'radio-station' );
__( 'Radio Clock', 'radio-station' );
__( 'Radio Timezone', 'radio-station' );
__( 'Times Display', 'radio-station' );
__( 'Display radio clock or just timezone in Subscribe box.', 'radio-station' );
__( 'Email', 'radio-station' );
__( 'Alt Email', 'radio-station' );
__( 'Calendar', 'radio-station' );
__( 'RSS', 'radio-staiton' );
__( 'Enabled Methods', 'radio-station' );
__( 'Show reminder methods available to all subscribers. (See OneSignal section for additional methods.', 'radio-station' );
__( 'Reminder Logging', 'radio-station' );
__( 'Log reminder successes and failures for debugging purposes.', 'radio-station' );
__( 'From Email Address', 'radio-station' );
__( 'Set the email address from which Subscriber Login and Reminder emails are sent.', 'radio-station' );
__( 'Email From Name', 'radio-station' );
__( 'Set the name from which Subscriber Login and Reminder emails are sent.', 'radio-station' );
__( 'Calendar Subscriptions', 'radio-station' );
__( 'Email subject template used for sending show start alerts by email.', 'radio-station' );
__( 'Reminder Email Body', 'radio-station' );
__( 'Email body template used whennn sending show start alerts by Email.', 'radio-station' );
__( 'OneSignal Integration', 'radio-station' );
__( 'Enable OneSignal subscription reminder integration.', 'radio-station' );
__( 'OneSignal App ID', 'radio-station' );
__( 'OneSignal App ID, required for subscribing users to OneSignal service.', 'radio-station' );
__( 'OneSignal API Key', 'radio-station' );
__( 'OneSignal API key, required for sending out reminder notifications.', 'radio-station' );
__( 'Phone Push', 'radio-station' );
__( 'Enable OneSignal phone push app alerts. Requires Radio Your Way App.', 'radio-station' );
__( 'Browser Push', 'radio-station' );
__( 'Enable OneSignal web browser show alerts.', 'radio-station' );
__( 'SMS Alerts', 'radio-station' );
__( 'Enable SMS text messages via OneSignal.', 'radio-station' );
__( 'Push Alert Title', 'radio-station' );
__( 'Title template for Push Notification Alerts.', 'radio-station' );
__( 'Starting Now Title', 'radio-station' );
__( 'Title template for Push Notifications when prewarning minutes are 0.', 'radio-station' );
__( 'Message template for Push Notifications Alerts.', 'radio-station' );
__( 'Enable Tap Pages', 'radio-station' );
__( 'Enable responsive Mobile App Menu via the included Tap Pages plugin.', 'radio-station' );
__( '', 'radio-station' );
__( 'Configure via Tap Pages settings page.', 'radio-station' );
__( 'Enable Integration', 'radio-station' );
__( 'Enable integration with Radio Your Way app.', 'radio-station' );
__( 'App Scheme', 'radio-station' );
__( 'Optional custom app scheme prefix to use for app redirections.', 'radio-station' );
__( 'Download Image Color', 'radio-station' );
__( 'White', 'radio-station' );
__( 'Black', 'radio-station' );
__( 'Red', 'radio-station' );
__( 'Blue', 'radio-station' );
__( 'Default button iamge color for App Download icons.', 'radio-station' );
__( 'Latest Android Version', 'radio-station' );
__( 'Your latest released app version in the Google Store.', 'radio-station' );
__( 'Package ID', 'radio-station' );
__( 'Google Play package ID used to generate app download and update links. eg. myapp.host.com', 'radio-station' );
__( 'Store Country', 'radio-station' );
__( 'Google Play Store country for app linking.', 'radio-station' );
__( 'Latest Apple Version', 'radio-station' );
__( 'Your latest release app version in the Apple Store.', 'radio-station' );
__( 'Bundle ID', 'radio-station' );
__( 'Apple Connect bundle ID used to generate app download and update links. eg. myapp.host.com', 'radio-station' );
__( 'Apple Store country for app linking.', 'radio-station' );
__( 'General', 'radio-station' );
__( 'Player', 'radio-station' );
__( 'Subscribe', 'radio-station' );
__( 'Pages', 'radio-station' );
__( 'Archives', 'radio-station' );
__( 'Widgets', 'radio-station' );
__( 'Roles', 'radio-station' );
__( 'App', 'radio-station' );
__( 'Subscribe Buttons', 'radio-station' );
__( 'Login Options', 'radio-station' );
__( 'Subscription Methods', 'radio-station' );
__( 'Mobile App Menu', 'radio-station' );
__( 'Radio Your Way App', 'radio-station' );
__( 'Android App Details', 'radio-station' );
__( 'Apple App Details', 'radio-station' );
__( 'Reminder Emails', 'radio-station' );
__( 'Radio Station needs to be installed and activated to use %s.', 'radio-station' );
__( 'Activate Radio Station', 'radio-station' );
__( 'Install Radio Station', 'radio-station' );
__( 'Your Radio Station plugin needs to be updated to work with %s.', 'radio-station' );
__( 'The required minimum version of the Radio Station plugin is:', 'radio-station' );
__( 'Update to Radio Station', 'radio-station' );
__( 'Development Version', 'radio-station' );
__( 'Sorry, you are not allowed to update plugins for this site.', 'radio-station' );
__( 'Update Plugin via Github', 'radio-station' );
__( 'Error. Could not connect to filesystem. Please install plugin update manually.', 'radio-station' );
__( 'Error. Downloading the plugin package failed. Please try again.', 'radio-station' );
__( 'Downloaded plugin package from:', 'radio-station' );
__( 'Package unzipped successfully.', 'radio-station' );
__( 'Package contents moved to plugin directory.', 'radio-station' );
__( 'The plugin has been updated, but could not be reactivated. Please reactivate it manually.', 'radio-station' );
__( 'The previous version of the plugin has been backed up if you need to restore it.', 'radio-station' );
__( 'Plugin reactivated successfully.', 'radio-station' );
__( 'Radio Station Settings', 'radio-station' );
__( 'Back to Plugins page.', 'radio-station' );
__( 'Your session has timed out. Please login again!', 'radio-station' );
__( 'Android App', 'radio-station' );
__( 'Installed', 'radio-station' );
__( 'Latest', 'radio-station' );
__( 'Apple App', 'radio-station' );
__( 'Upgrade Now', 'radio-station' );
__( 'Your Show %s starts in %d minutes.', 'radio-station' );
__( 'Yes', 'radio-station' );
__( 'No', 'radio-station' );
__( '"%s" has just started.', 'radio-station' );
__( 'Start Audio Playback?', 'radio-station' );
__( 'your dial', 'radio-station' );
__( 'Enter Your Login Email', 'radio-station' );
__( 'Password', 'radio-station' );
__( 'Reset', 'radio-station' );
__( 'Login with Password', 'radio-station' );
__( 'Passwordless Login', 'radio-station' );
__( 'Send Magic Login Link', 'radio-station' );
__( 'Email address not found. Please recheck for typos.', 'radio-station' );
__( 'Login failed: ', 'radio-station' );
__( 'Successfully logged in.', 'radio-station' );
__( 'Error. Email address not found.', 'radio-station' );
__( 'Error. Email could not be sent. Try again?', 'radio-station' );
__( 'Email sent. Click on the link to verify your address.', 'radio-station' );
__( 'Error. Please recheck your email entry.', 'radio-station' );
__( 'A password reset was requested for the following account:', 'radio-station' );
__( 'Site Name: %s', 'radio-station' );
__( 'Username: %s', 'radio-station' );
__( 'To reset your password, visit the following address:', 'radio-station' );
__( 'If this was a mistake, ignore this email and nothing will happen.', 'radio-station' );
__( 'This password reset request originated from the IP address %s.', 'radio-station' );
__( '[%s] Password Reset Request', 'radio-station' );
__( 'Error', 'radio-station' );
__( 'Password reset email sent. Please check your inbox.', 'radio-station' );
__( 'Oops! Magic login email failed to send. Please try again.', 'radio-station' );
__( 'Sent! Click magic link in email or enter code to login.', 'radio-station' );
__( 'Sent! Click magic link in email to login.', 'radio-station' );
__( 'You are already logged in.', 'radio-station' );
__( 'You are already logged in and verified.', 'radio-station' );
__( 'Please recheck your email address for typos.', 'radio-station' );
__( 'That magic login code has expired.', 'radio-station' );
__( 'Success. You are now logged in.', 'radio-station' );
__( 'Attempts exceeded. Request new link.', 'radio-station' );
__( 'Magic login code mismatch.', 'radio-station' );
__( 'Phone', 'radio-station' );
__( 'Browser', 'radio-station' );
__( 'SMS', 'radio-station' );
__( 'Phone Alert Setup', 'radio-station' );
__( 'App not detected on this device.', 'radio-station' );
__( 'Phone Notification Permissions granted.', 'radio-station' );
__( 'Enable Phone Notifications', 'radio-station' );
__( 'Oops! Cannot Request Permissions', 'radio-station' );
__( "Please check your device's App installation.", 'radio-station' );
__( 'Browser Alert Setup', 'radio-station' );
__( 'Failed to load required script for browser notifications.', 'radio-station' );
__( 'Try disabling script blockers for this site.', 'radio-station' );
__( 'App detected. Use phone alerts for app notifications instead.', 'radio-station' );
__( 'Browser Notifications Permissions granted.', 'radio-station' );
__( 'To ensure notifications are received, please make sure to select the "Forever" timeframe when granting browser permissions.', 'radio-station' );
__( 'You can enable or disable all browser alerts at any time via this panel without needing to adjust browser settings.', 'radio-station' );
__( 'Enable Browser Notifications', 'radio-station' );
__( "Please check your browser's permission settings.", 'radio-station' );
__( 'SMS Text Message Setup', 'radio-station' );
__( 'Remove Phone Number', 'radio-station' );
__( 'Enter Phone Number', 'radio-station' );
__( 'Add Phone Number', 'radio-station' );
__( 'Every Minute', 'radio-station' );
__( 'Subscribe to %s', 'radio-station' );
__( 'Subscribe to Shows.', 'radio-station' );
__( 'Manage Your Show Subscriptions', 'radio-station' );
__( 'Manage Subscriptions', 'radio-station' );
__( 'Subscribe to Show', 'radio-station' );
__( 'Subscribe to this Show', 'radio-station' );
__( 'Subscribe to a Show', 'radio-station' );
__( 'Login', 'radio-station' );
__( 'Upcoming', 'radio-station' );
__( 'Manage', 'radio-station' );
__( 'Settings', 'radio-station' );
__( 'Already a Subscriber?' , 'radio-station' );
__( 'Click here to Login', 'radio-station' );
__( 'Your Email', 'radio-station' );
__( 'Verified', 'radio-station' );
__( 'Unverified', 'radio-station' );
__( 'Default Prewarning', 'radio-station' );
__( 'minutes', 'radio-station' );
__( 'Reminder Methods', 'radio-station' );
__( 'Update Settings', 'radio-station' );
__( 'Subscription Settings Updated.', 'radio-station' );
__( 'Show', 'radio-station' );
__( 'Select Show...', 'radio-station' );
__( 'Specials', 'radio-station' );
__( 'Alphabetical', 'radio-station' );
__( 'Monthly or Irregular', 'radio-station' );
__( 'Not Currently Scheduled', 'radio-station' );
__( 'Select Show Shift(s', 'radio-station' );
__( 'Please select a Show to Subscribe to.', 'radio-station' );
__( 'After subscribing, you can get Show start alerts by', 'radio-station' );
__( 'or', 'radio-station' );
__( 'Subscribed to Show.', 'radio-station' );
__( 'Subscriptions Updated.', 'radio-station' );
__( 'Show Subscription Removed.', 'radio-station' );
__( 'Timeslot', 'radio-station' );
__( 'Alerts', 'radio-station' );
__( 'Prewarn', 'radio-station' );
__( 'No Show Shifts found to display.', 'radio-station' );
__( 'Date', 'radio-station' );
__( 'Start', 'radio-station' );
__( 'No Upcoming Shows to Display.', 'radio-station' );
__( 'Update Subscriptions', 'radio-station' );
__( 'No Show Subscriptions yet.', 'radio-station' );
__( 'Pause', 'radio-station' );
__( 'Default', 'radio-station' );
__( 'Custom', 'radio-station' );
__( 'RSS', 'radio-station' );
__( 'Email Notification Instructions', 'radio-station' );
__( 'Your email is verified and setup complete.', 'radio-station' );
__( 'Your email is not yet verified.', 'radio-station' );
__( 'To complete set up for receiving email alerts,', 'radio-station' );
__( 'click on the link in your verification email.', 'radio-station' );
__( 'Resend Verification Email', 'radio-station' );
__( 'Calendar Sync Instructions', 'radio-station' );
__( 'Your personal Calendar URL is:', 'radio-station' );
__( 'Copy to Clipboard', 'radio-station' );
__( 'Calendar Client Instructions', 'radio-station' );
__( 'Google Calendar', 'radio-station' );
__( 'Apple Calendar (macOS', 'radio-station' );
__( 'Apple Calendar (iOS', 'radio-station' );
__( 'Outlook.Com', 'radio-station' );
__( 'Outlook (Desktop', 'radio-station' );
__( 'Thunderbird', 'radio-station' );
__( 'RSS Notification Instructions', 'radio-station' );
__( 'All Show Timeslots', 'radio-station' );
__( 'to', 'radio-station' );
__( 'Are you sure you want to remove all subscriptions for this Show?', 'radio-station' );
__( 'Error! Show ID must be numeric.', 'radio-station' );
__( 'Error! Show ID not found!', 'radio-station' );
__( 'Oops! Provided email address is empty. Please try again!', 'radio-station' );
__( 'Oops! Provided email address is invalid. Please try again!', 'radio-station' );
__( 'That email is already registered. Please login instead.', 'radio-station' );
__( 'Error. User could not be created. Please try again.', 'radio-station' );
__( 'Error. Verification email could not be sent. Please try again.', 'radio-station' );
__( 'Subscription created. Please click the link in your email to verify your address to continue.', 'radio-station' );
__( 'Error! Station ID must be numeric.', 'radio-station' );
__( 'Error! Channel ID must be numeric.', 'radio-station' );
__( 'Timezone', 'radio-station' );
__( 'Your Zone', 'radio-station' );
__( 'Change Timezone', 'radio-station' );
__( 'Time', 'radio-station' );
__( 'You', 'radio-station' );
__( 'Show times display in your timezone.', 'radio-station' );
__( 'Select Region...', 'radio-station' );
__( 'Clear', 'radio-station' );
__( 'Cancel', 'radio-station' );
__( 'Select Timezone...', 'radio-station' );
